development:
  access_key_id: AKIAJRAOBHNMUM6STG2A
  secret_access_key: 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

production:
  access_key_id: "AKIAJRAOBHNMUM6STG2A"
  secret_access_key: "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"