development:
  access_key_id: ENV['AWS_access_key_id']
  secret_access_key: ENV['AWS_secret_access_key']

production:
  access_key_id: ENV['AWS_access_key_id']
  secret_access_key: ENV['AWS_secret_access_key']